
package com.sdi.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-24T13:27:42.502+02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "BusinessException", targetNamespace = "http://business.sdi.impl/")
public class BusinessException_Exception extends Exception {
    
    private com.sdi.ws.BusinessException businessException;

    public BusinessException_Exception() {
        super();
    }
    
    public BusinessException_Exception(String message) {
        super(message);
    }
    
    public BusinessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException_Exception(String message, com.sdi.ws.BusinessException businessException) {
        super(message);
        this.businessException = businessException;
    }

    public BusinessException_Exception(String message, com.sdi.ws.BusinessException businessException, Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    public com.sdi.ws.BusinessException getFaultInfo() {
        return this.businessException;
    }
}
