package com.sdi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-24T13:27:42.523+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://business.sdi.impl/", name = "EjbUsuariosService")
@XmlSeeAlso({ObjectFactory.class})
public interface EjbUsuariosService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProfesores", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.GetProfesores")
    @WebMethod
    @ResponseWrapper(localName = "getProfesoresResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.GetProfesoresResponse")
    public java.util.List<com.sdi.ws.Usuario> getProfesores();

    @RequestWrapper(localName = "actualizarPerfil", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarPerfil")
    @WebMethod
    @ResponseWrapper(localName = "actualizarPerfilResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarPerfilResponse")
    public void actualizarPerfil(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sdi.ws.Usuario arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verExpediente", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerExpediente")
    @WebMethod
    @ResponseWrapper(localName = "verExpedienteResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerExpedienteResponse")
    public java.util.List<com.sdi.ws.Matricula> verExpediente(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarProfesores", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarProfesores")
    @WebMethod
    @ResponseWrapper(localName = "buscarProfesoresResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarProfesoresResponse")
    public java.util.List<com.sdi.ws.Usuario> buscarProfesores(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verUsuariosDesactivados", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerUsuariosDesactivados")
    @WebMethod
    @ResponseWrapper(localName = "verUsuariosDesactivadosResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerUsuariosDesactivadosResponse")
    public java.util.List<com.sdi.ws.Usuario> verUsuariosDesactivados();

    @RequestWrapper(localName = "insertarUsuario", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.InsertarUsuario")
    @WebMethod
    @ResponseWrapper(localName = "insertarUsuarioResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.InsertarUsuarioResponse")
    public void insertarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    ) throws BusinessException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verUsuariosActivados", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerUsuariosActivados")
    @WebMethod
    @ResponseWrapper(localName = "verUsuariosActivadosResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.VerUsuariosActivadosResponse")
    public java.util.List<com.sdi.ws.Usuario> verUsuariosActivados();

    @RequestWrapper(localName = "actualizarPassword", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarPassword")
    @WebMethod
    @ResponseWrapper(localName = "actualizarPasswordResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarPasswordResponse")
    public void actualizarPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "activarUsuario", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActivarUsuario")
    @WebMethod
    @ResponseWrapper(localName = "activarUsuarioResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActivarUsuarioResponse")
    public com.sdi.ws.Usuario activarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarUsuariosDesactivados", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarUsuariosDesactivados")
    @WebMethod
    @ResponseWrapper(localName = "buscarUsuariosDesactivadosResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarUsuariosDesactivadosResponse")
    public java.util.List<com.sdi.ws.Usuario> buscarUsuariosDesactivados(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarUsuariosActivados", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarUsuariosActivados")
    @WebMethod
    @ResponseWrapper(localName = "buscarUsuariosActivadosResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.BuscarUsuariosActivadosResponse")
    public java.util.List<com.sdi.ws.Usuario> buscarUsuariosActivados(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "actualizarNota", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarNota")
    @WebMethod
    @ResponseWrapper(localName = "actualizarNotaResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.ActualizarNotaResponse")
    public void actualizarNota(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "desactivarUsuario", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.DesactivarUsuario")
    @WebMethod
    @ResponseWrapper(localName = "desactivarUsuarioResponse", targetNamespace = "http://business.sdi.impl/", className = "com.sdi.ws.DesactivarUsuarioResponse")
    public com.sdi.ws.Usuario desactivarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
